spring:
  application:
    name: shopping-cart-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

book-service:
  ribbon:
    listOfServers: http://localhost:8000,http://localhost:8001